# Generated by Django 4.1.3 on 2022-11-30 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gothrow', '0002_customuser_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('holes', models.IntegerField()),
                ('course_lat', models.DecimalField(blank=True, decimal_places=5, max_digits=7)),
                ('course_long', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_num', models.IntegerField(blank=True)),
                ('par', models.IntegerField(blank=True)),
                ('length', models.IntegerField(blank=True)),
                ('hole_lat', models.DecimalField(blank=True, decimal_places=5, max_digits=7)),
                ('hole_long', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.course')),
            ],
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.course')),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.scores')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.rounds')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.scores')),
            ],
        ),
        migrations.CreateModel(
            name='HoleScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.hole')),
                ('scores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.scores')),
            ],
        ),
    ]
