# Generated by Django 4.1.3 on 2022-12-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gothrow', '0003_course_hole_rounds_scores_remove_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.course')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gothrow.hole')),
            ],
        ),
    ]
