# Generated by Django 4.1.3 on 2022-12-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gothrow', '0004_coursehole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseHole',
        ),
    ]
