# Generated by Django 4.1.3 on 2022-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gothrow', '0007_rounds_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
