# Generated by Django 4.1.3 on 2022-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gothrow', '0008_alter_rounds_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
