# Generated by Django 4.1.3 on 2022-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gothrow', '0009_alter_scores_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_par',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
